default: &default
  adapter: postgresql
  encoding: unicode
  pool: 1
  host: <%= ENV['DB_PATH'] || 'localhost' %>
  username: postgres
  password: postgres
  database: postgres
  port: <%= ENV['DB_PORT'] || 5555 %>

development:
  <<: *default

test:
  <<: *default
  
production:
  <<: *default
