version: '3.4'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5555:5432'
    volumes: 
      - db:/var/lib/postgresql/data

  bloggin:
    depends_on:
      - db
    image: bloggin
    build:
      context: ./server/ruby
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    links: 
      - db

volumes:
  db:
    driver: local