version: '3.4'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5555:5432'
    volumes:
      - db:/var/lib/postgresql/data

  ruby:
    depends_on:
      - db
    image: ruby
    build:
      context: ./server/ruby
      dockerfile: Dockerfile
    env_file:
      - ./server/ruby/.docker_env
    ports:
      - 3500:3500
    links:
      - db

volumes:
  db:
    driver: local
